name: LaTeX compile
on:
  push:
    paths:
      - ".github/workflows/latex.yml"
      - "latex/*.tex"
jobs:
  compile:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: xu-cheng/latex-action@v2
        with:
          root_file: "*.tex"
          glob_root_file: true
          working_directory: latex
          latexmk_use_lualatex: true
      - run: |
          mkdir -p public/latex
          mv latex/*.pdf public/latex
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
